version: '2.0'
services:
  frontend:
    container_name: GS-front-react-sandbox
    image: node:latest
    volumes:
      - ./build:/build
    ports:
      - 3000:3000
    entrypoint:
      [
        sh,
        -c,
        'npm i serve -g && serve -s build',
      ]
