version: '2.0'
services:
  frontend:
    image: node:latest
    # env_file:
    # - .env
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./app:/app
    expose:
      - '3000'
    entrypoint:
      [
        sh,
        -c,
        'cd /app && yarn install && yarn build && npm i serve -g && serve -s build',
      ]
  nginx:
    image: nginx:alpine
    tty: true
    # env_file:
    # - .env
    depends_on:
      - frontend
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./templates:/etc/nginx/templates
      - ./docker/config/conf.d:/etc/nginx/conf.d/
      # - ./docker/config/log:/var/log/nginx/
      # - ./docker/config/cert:/etc/nginx/cert/
    ports:
      - 443:443
      - 80:80
    links:
      - frontend
