version: '2.0'
services:
  frontend:
    container_name: GS-front-react
    image: node:latest
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    entrypoint:
      [
        sh,
        -c,
        'cd /app && npm i serve -g && serve -s build',
      ]
